/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.VinilVO;
import servicos.ServicosFactory;
import servicos.VinilServicos;

/**
 *
 * @author Natan Fraga 
 * @since 15:51 - 10/07/2018
 * @version Vinil II
 */
public class GuiManutencaoVinil extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"Código", "Nome", "Descrição", "Preço", "Gênero", "Gravadora"});
    /**
     * Creates new form GuiManutencaoVinil
     */
    public GuiManutencaoVinil() {
        initComponents();
        buscarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableVinis = new javax.swing.JTable();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbBuscar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jcomboFiltro = new javax.swing.JComboBox<>();
        jtPesquisa = new javax.swing.JTextField();
        jLayeredPane14 = new javax.swing.JLayeredPane();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jtPreco = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        jtGravadora = new javax.swing.JTextField();
        jlGenero = new javax.swing.JLabel();
        jlGravadora = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção do VINIL");

        jlpDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jtableVinis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço", "Gênero", "Gravadora"
            }
        ));
        jtableVinis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableVinisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableVinis);

        jlpDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jbLimpar)
                    .addComponent(jbDeletar)
                    .addComponent(jbAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jcomboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Descrição", "Preço", "Gênero", "Gravadora", " " }));
        jcomboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFiltroItemStateChanged(evt);
            }
        });

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jLayeredPane1.setLayer(jcomboFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jlCodigo.setText("Código");
        jLayeredPane14.add(jlCodigo);
        jlCodigo.setBounds(20, 30, 70, 14);

        jlNome.setText("Nome");
        jLayeredPane14.add(jlNome);
        jlNome.setBounds(20, 70, 70, 14);

        jlDescricao.setText("Descrição");
        jLayeredPane14.add(jlDescricao);
        jlDescricao.setBounds(20, 110, 70, 14);

        jlPreco.setText("Preço");
        jLayeredPane14.add(jlPreco);
        jlPreco.setBounds(20, 150, 50, 14);

        jbConfirmarAlteracao.setText("Confirmar alteração");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });
        jLayeredPane14.add(jbConfirmarAlteracao);
        jbConfirmarAlteracao.setBounds(390, 120, 160, 30);

        jtCodigo.setEnabled(false);
        jLayeredPane14.add(jtCodigo);
        jtCodigo.setBounds(110, 20, 210, 30);
        jLayeredPane14.add(jtNome);
        jtNome.setBounds(110, 60, 210, 30);
        jLayeredPane14.add(jtDescricao);
        jtDescricao.setBounds(110, 100, 210, 30);
        jLayeredPane14.add(jtPreco);
        jtPreco.setBounds(110, 140, 210, 30);
        jLayeredPane14.add(jtGenero);
        jtGenero.setBounds(110, 180, 210, 30);
        jLayeredPane14.add(jtGravadora);
        jtGravadora.setBounds(110, 220, 210, 30);

        jlGenero.setText("Gênero");
        jLayeredPane14.add(jlGenero);
        jlGenero.setBounds(20, 190, 40, 14);

        jlGravadora.setText("Gravadora");
        jLayeredPane14.add(jlGravadora);
        jlGravadora.setBounds(20, 230, 60, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados)
                    .addComponent(jLayeredPane14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void buscarTabela() {
        try {
            List<VinilVO> vinis;
            VinilServicos vs = ServicosFactory.getVinilServicos();
            vinis = vs.buscarVinis();
            
            limparTabela();
            
            for (int i = 0; i < vinis.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(vinis.get(i).getIdVinil()),
                    String.valueOf(vinis.get(i).getNome()),
                    String.valueOf(vinis.get(i).getDescricao()),
                    String.valueOf(vinis.get(i).getPreco()),
                    String.valueOf(vinis.get(i).getGenero()),
                    String.valueOf(vinis.get(i).getGravadora())});
            }
            jtableVinis.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRO NO SISTEMA! "+e.getMessage());
        }
    }//fecha buscarTabela
    
    private void limparTabela(){
        dtm.setNumRows(0);
    }//fecha limparTabela
    
    private void deletar(){
        try {
            int linha = jtableVinis.getSelectedRow();
            
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Selecione uma linha! ");
            } else {
                String id = jtableVinis.getValueAt(linha, 0).toString();
                VinilServicos vs = ServicosFactory.getVinilServicos();
                vs.deletarVinil(Long.parseLong(id));
                
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Produto excluído com sucesso! ");
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "ERRO NO SISTEMA "+e.getMessage());
        }//fecha catch
    }//fecha deletar
    
    private void filtrar(){
        try {
            if (jtPesquisa.getText().isEmpty()) {
                limparTabela();
                buscarTabela();
            } else {
                String query = "";
                String filtro = jcomboFiltro.getSelectedItem().toString();
                
                if (filtro.equalsIgnoreCase("Código")) {
                    query="where idvinil like '%"+jtPesquisa.getText()+"%'";
                } else if (filtro.equalsIgnoreCase("Nome")){
                    query="where nome like '%"+jtPesquisa.getText()+"%'";
                } else if (filtro.equalsIgnoreCase("Descrição")){
                    query="where descricao like '%"+jtPesquisa.getText()+"%'";
                } else if (filtro.equalsIgnoreCase("Preço")){
                    query="where preco like '%"+jtPesquisa.getText()+"%'";
                } else if (filtro.equalsIgnoreCase("Gênero")){
                    query="where genero like '%"+jtPesquisa.getText()+"%'";
                } else if (filtro.equalsIgnoreCase("Gravadora")){
                    query="where gravadora like '%"+jtPesquisa.getText()+"%'";
                }//fecha if
                
                VinilServicos vs = ServicosFactory.getVinilServicos();
                //TODO
                List<VinilVO> vinil = vs.filtrar(1);
                
                for (int i = 0; i <vinil.size(); i++) {
                    dtm.addRow(new String[]{
                    String.valueOf(vinil.get(i).getIdVinil()),
                    String.valueOf(vinil.get(i).getNome()),
                    String.valueOf(vinil.get(i).getDescricao()),
                    String.valueOf(vinil.get(i).getPreco()),
                    String.valueOf(vinil.get(i).getGenero()),
                    String.valueOf(vinil.get(i).getGravadora())});
                }//fecha for
                
                jtableVinis.setModel(dtm);
            }//fecha if
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "ERRO NO SISTEMA"+e.getMessage());
        }//fecha catch
    }//fecha filtrar
    
    private void alterar(){
        int linha = jtableVinis.getSelectedRow();
        if (linha != -1){
            jtCodigo.setText((String)jtableVinis.getValueAt(linha, 0));
            jtNome.setText((String)jtableVinis.getValueAt(linha, 1));
            jtDescricao.setText((String)jtableVinis.getValueAt(linha, 2));
            jtPreco.setText((String)jtableVinis.getValueAt(linha, 3));
            jtGenero.setText((String)jtableVinis.getValueAt(linha, 4));
            jtGravadora.setText((String)jtableVinis.getValueAt(linha, 5));
        } else {
            JOptionPane.showMessageDialog(this, 
              "Você não selecionou nenhuma linha!");
        }//fecha else      
    }//fecha alterar 
    
    private void confirmarAlteracao(){
        try {
        VinilVO vVO = new VinilVO();
        
            vVO.setIdVinil(Long.parseLong(jtCodigo.getText()));
            vVO.setNome(jtNome.getText());
            vVO.setDescricao(jtDescricao.getText());
            vVO.setPreco(Double.parseDouble(jtPreco.getText()));
            vVO.setGenero(jtGenero.getText());
            vVO.setGravadora(jtGravadora.getText());

            VinilServicos vs = ServicosFactory.getVinilServicos();

            vs.alterarVinil(vVO);
            
            JOptionPane.showMessageDialog(this,
                    "Vinil ALTERADO com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRO NO SISTEMA! "+e.getMessage());
        }//fecha catch            
    }//fecha confirmarAlteracao 
    
    private void limparCampos(){
        jtCodigo.setText("");
        jtNome.setText("");
        jtDescricao.setText("");
        jtPreco.setText("");
        jtGenero.setText("");
        jtGravadora.setText("");
    }//fecha limparCampos
    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        limparTabela();
        buscarTabela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        // TODO add your handling code here:
        deletar();
        limparTabela();
        buscarTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        // TODO add your handling code here:
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jcomboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFiltroItemStateChanged
        // TODO add your handling code here:
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jcomboFiltroItemStateChanged

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        confirmarAlteracao();
        limparTabela();
        buscarTabela();
        limparCampos();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed

    private void jtableVinisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableVinisMouseClicked
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_jtableVinisMouseClicked

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcomboFiltro;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlGravadora;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtGravadora;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTable jtableVinis;
    // End of variables declaration//GEN-END:variables
}
