/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.UIManager;

/**
 *
 * @author Natan Fraga
 * @since 10:24 - 10/07/2018
 * @version Vinil II
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadMusica = new javax.swing.JMenuItem();
        jmiCadVinil = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManMusica = new javax.swing.JMenuItem();
        jmiManVinil = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");

        jmiCadMusica.setText("Música");
        jmiCadMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadMusicaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadMusica);

        jmiCadVinil.setText("Vinil");
        jmiCadVinil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadVinilActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadVinil);

        jMenuBar.add(jmCadastro);

        jmManutencao.setText("Manutenção");

        jmiManMusica.setText("Música");
        jmiManMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManMusicaActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManMusica);

        jmiManVinil.setText("Vinil");
        jmiManVinil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManVinilActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManVinil);

        jMenuBar.add(jmManutencao);

        jmSair.setText("Sair");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmSair.add(jmiSair);

        jMenuBar.add(jmSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void abrirCadMusica(){
        GuiCadMusica gcm = new GuiCadMusica();
        jAreaTrabalho.add(gcm);
        gcm.setVisible(true);
    }//fecha método abrirCadMusica
    
    private void abrirCadVinil(){
        GuiCadVinil gcd = new GuiCadVinil();
        jAreaTrabalho.add(gcd);
        gcd.setVisible(true);
    }//fecha método abrirCadVinil
    
    private void abrirManMusica(){
        GuiManutencaoMusica gmm = new GuiManutencaoMusica();
        jAreaTrabalho.add(gmm);
        gmm.setVisible(true);
    }//fecha método abrirManMusica
    
    private void abrirManVinil(){
        GuiManutencaoVinil gmv = new GuiManutencaoVinil();
        jAreaTrabalho.add(gmv);
        gmv.setVisible(true);
    }//fecha método abrirManVinil
    

    private void jmiCadVinilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadVinilActionPerformed
        // TODO add your handling code here:
        abrirCadVinil();
    }//GEN-LAST:event_jmiCadVinilActionPerformed

    private void jmiCadMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadMusicaActionPerformed
        // TODO add your handling code here:
        abrirCadMusica();
    }//GEN-LAST:event_jmiCadMusicaActionPerformed

    private void jmiManVinilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManVinilActionPerformed
        // TODO add your handling code here:
        abrirManVinil();
    }//GEN-LAST:event_jmiManVinilActionPerformed

    private void jmiManMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManMusicaActionPerformed
        // TODO add your handling code here:
        abrirManMusica();
    }//GEN-LAST:event_jmiManMusicaActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {    
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Red", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadMusica;
    private javax.swing.JMenuItem jmiCadVinil;
    private javax.swing.JMenuItem jmiManMusica;
    private javax.swing.JMenuItem jmiManVinil;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
